version: '3.7'

services:

  api-consolidado-diario:
    image: api-consolidado-diario
    deploy:
      replicas: 3
    build:
      dockerfile: Dockerfile
    ports:
      - target: 80

  # sql-server:
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   environment:
  #     SA_PASSWORD: Numsey#2022
  #     ACCEPT_EULA: "Y"
  #     MSSQL_PID: "Developer"
  #   ports:
  #     - "1433:1433"

networks:
  default:
    name: my-network
    driver: bridge
    external: true